Pipeline:
  name: foo

GitRepo:
  name: sampleRepo
  gitProvider: myGitIntegration
  path: jfrog/jfrog-pipelines
  branches:
    include: {{gitBranch}}

artifactoryIntegration: myArtifactoryIntegration

Image:
  name: sampleImage
  sourceRepository: foo
  autoPull: false

DockerBuild:
  name: sampleBuild
  dockerImageName: jfrog/testimage
  dockerFileName: Dockerfile
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

DockerPush:
  name: samplePush

BuildInfo:
  autoPublishBuildInfo: true
  name: sampleBuildInfo
