Pipeline:
  name: build_push_app

GitRepo:
  name: app_git_repo
  gitProvider: bharathGithub
  path: bharath92/jfrog-pipelines
  branches:
    include: {{gitBranch}}

artifactoryIntegration: myArtIntegration

Image:
  name: app_docker_image
  sourceRepository: foo
  autoPull: false

DockerBuild:
  name: app_image_build
  dockerImageName: stg-repo.jfrog.info/templates-docker-local/dbp
  dockerFileName: Dockerfile
  dockerFileLocation: './.jfrog-pipelines/template-DockerBuildAndPush'
  dockerImageTag: ${run_number}

DockerPush:
  name: app_image_push
  targetRepository: templates-docker-local

BuildInfo:
  autoPublishBuildInfo: true
  name: image_build_info
